var traits = {
  powerful: {
    key: "powerful",
    type: "size",
    subtype: "medium",
    title: "Powerful Build",
    description: "You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift.",
    cost: 2
  },
  strong: {
    key: "strong",
    type: "size",
    subtype: "medium",
    title: "Strong",
    description: "Your speed is not reduced by wearing heavy armor.",
    cost: 2
  },
  reach: {
    key: "reach",
    type: "size",
    subtype: "medium",
    title: "Reach",
    description: "When you make a melee attack on your turn, your reach is 5 feet greater than normal.",
    cost: 5
  },
  nimble: {
    key: "nimble",
    type: "size",
    subtype: "small",
    title: "Nimble",
    description: "You can move through the space of any creature that is of a size larger than yours.",
    cost: 2
  },
  smallstealth: {
    key: "smallstealth",
    type: "size",
    subtype: "small",
    title: "Small Stealth",
    description: "You can attempt to hide even when you are obscured only by a creature that is at least one size larger than you.",
    cost: 4
  },
  quick: {
    key: "quick",
    type: "speed",
    title: "Quick",
    description: "Your base walking speed is <strong>35 feet</strong>.",
    value: "35 ft.",
    traittype: "property",
    options: {
      type: "speed",
      value: "35 ft."
    },
    cost: 2,
    isExclusive: true
  },
  speedy: {
    key: "speedy",
    type: "speed",
    title: "Speedy",
    description: "Your base walking speed is <strong>40 feet</strong>.",
    value: "40 ft.",
    traittype: "property",
    options: {
      type: "speed",
      value: "40 ft."
    },
    cost: 6,
    isExclusive: true
  },
  darkvision: {
    key: "darkvision",
    type: "vision",
    title: "Darkvision",
    description: "You can see in dim light within 60 feet of you as if it were bright light, and in darkness as if it were dim light. You can't discern color in darkness, only shades of gray.",
    value: "Darkvision (60ft.)",
    traittype: "property",
    options: {
      type: "vision",
      value: "Darkvision (60ft.)"
    },
    cost: 3,
    isExclusive: true
  },
  darkvision2: {
    key: "darkvision2",
    type: "vision",
    title: "Superior Darkvision",
    description: "You can see in dim light within 120 feet of you as if it were bright light, and in darkness as if it were dim light. You can't discern color in darkness, only shades of gray.",
    value: "Darkvision (120ft.)",
    traittype: "property",
    options: {
      type: "vision",
      value: "Darkvision (120ft.)"
    },
    cost: 4,
    isExclusive: true
  },
  celestialcantrip: {
    key: "celestialcantrip",
    type: "bloodline",
    subtype: "celestial",
    title: "Cantrip",
    description: "You know the light or dancing lights cantrip.",
    traittype: "spellfromlist",
    options: ["light", "dancinglights"],
    duplicate: "cantrip",
    cost: 2
  },
  healinghands: { 
    key: "healinghands", 
    type: "bloodline", 
    subtype: "celestial", 
    title: "Healing Hands", 
    description: "As an action, you can touch a creature and roll a number of d4s equal to your Proficiency Bonus. The creature regains a number of hit points equal to the total rolled. Once you use this trait, you can't use it again until you finish a long rest.",
    cost: 3 },
  celestialresistance: { 
    key: "celestialresistance", 
    type: "bloodline", 
    subtype: "celestial", 
    title: "Celestial Resistance", 
    description: "You have resistance to one of the following damage types: radiant or necrotic.",
    traittype: "select",
    options: {
      type: "damagetype",
      options: ["radiant", "necrotic"]
    },
    cost: 3 },
  celestialinnatemagic: { 
    key: "celestialinnatemagic", 
    type: "bloodline", 
    subtype: "celestial", 
    title: "Innate Magic", 
    description: "Choose one 1st-level spell from the cleric list. You can cast the chosen spell once with this trait and regain the ability to do so when you finish a long rest. You can also cast this spell using any spell slots you have.",
    traittype: "spellgranted",
    options: {
      level: 1,
      classlist: "cleric"
    },
    cost: 3 },
  celestialrevelation: { 
    key: "celestialrevelation", 
    type: "bloodline", 
    subtype: "celestial", 
    title: "Celestial Revelation", 
    description: "When you reach 3rd level, you can use a bonus action to unleash the celestial energy inside yourself. The benefits of that transformation last for 1 minute or until you end it as a bonus action. Once you transform you can't use it again until you finish a long rest. Choose one:",
    traittype: "choice",
    options: [
      {
        key: "necroticshroud",
        title: "1",
        description: "FPO",
      }, {
        key: "radiantconsumption",
        title: "2",
        description: "FPO",
      }, {
        key: "radiantsoul",
        title: "3",
        description: "FPO",
      }
    ],
    cost: 5 },
  elementalattunement: { 
    key: "elementalattunement", 
    type: "bloodline", 
    subtype: "elemental", 
    title: "Elemental Attunement", 
    description: "If you have elemental ancestry, you must take this trait. Choose one of the following damage types: acid, cold, fire, lightning, or thunder.",
    traittype: "select",
    options: {
      type: "resistance",
      acid: "Acid",
      cold: "Cold",
      fire: "Fire",
      lightning: "Lightning",
      thunder: "Thunder"
    },
    required: true,
    cost: 0 },
  unendingbreath: { 
    key: "unendingbreath", 
    type: "bloodline", 
    subtype: "elemental", 
    title: "Unending Breath", 
    description: "You can hold your breath indefinitely while you're not incapacitated.",
    cost: 1 },
  earthwalk: { 
    key: "earthwalk", 
    type: "bloodline", 
    subtype: "elemental", 
    title: "Earth Walk", 
    description: "You can move across difficult terrain without expending extra movement when using your walking speed on the ground or the floor.",
    cost: 1 },
  elementalcantrip: { 
    key: "elementalcantrip", 
    type: "bloodline", 
    subtype: "elemental", 
    title: "Cantrip", 
    description: "You know one cantrip of your choice that deals damage of the type associated with your elemental attunement. Examples:",
    traittype: "spellgrantedelemental",
    options: {
      acid: ["acidsplash","infestation","poisonspray"],
      cold: ["frostbite","rayoffrost"],
      fire: ["firebolt","greenflameblade"],
      lightning: ["lightninglure"],
      thunder: ["thunderclap"]
    },
    duplicate: "cantrip",
    cost: 2 },
  elementalresistance: { 
    key: "elementalresistance", 
    type: "bloodline", 
    subtype: "elemental", 
    title: "Elemental Resistance", 
    description: "You have resistance to the damage type associated with your elemental attunement.",
    cost: 3 },
  elementalinnatemagic: { 
    key: "elementalinnatemagic", 
    type: "bloodline", 
    subtype: "elemental", 
    title: "Innate Magic", 
    description: "Choose one 1st-level spell of your choice that deals damage of the type associated with your elemental attunement. You can cast the chosen spell once with this trait and regain the ability to do so when you finish a long rest. You can also cast this spell using any spell slots you have.",
    traittype: "spellgranted",
    options: {
      level: 1,
      classlist: "all"
    },
    cost: 3 },
  elementalinnatemagic: { 
    key: "elementalinnatemagic", 
    type: "bloodline", 
    subtype: "elemental", 
    title: "Innate Magic", 
    description: "Based on your elemental ancestry, you gain the following innate spellcasting ability. Once you cast these spells with this trait, you can't cast that spell again until you finish a long rest. You can also cast these spells using any spell slots you have of the appropriate spell level.",
    cost: 8
  },
  fey: {
    key: "fey",
    type: "bloodline",
    subtype: "fey",
    title: "Fey",
    description: "Your creature type is Fey.",
    cost: 1
  },
  trance: { 
    key: "trance", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Trance", 
    description: "You don't need to sleep, and magic can't put you to sleep. You can finish a long rest in 4 hours if you spend those hours in a trancelike meditation, during which you retain consciousness. Whenever you finish this trance, you can mystically gain two proficiencies that you don't have, each one with a weapon or tool of your choice.",
    cost: 2 },
  charmresistance: { 
    key: "charmresistance", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Charm Resistance", 
    description: "You have advantage on saving throws you make to avoid or end the charmed condition on yourself.",
    cost: 2 },
  feycantrip: { 
    key: "feycantrip", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Cantrip", 
    description: "You know the friends or druidcraft cantrip.",
    traittype: "spellfromlist",
    options: ["friends","druidcraft"],
    duplicate: "cantrip",
    cost: 2 },
  feyinnatemagic: { 
    key: "feyinnatemagic", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Innate Magic", 
    description: "Choose one 1st-level spell of your choice from the divination or enchantment school of magic. Once you cast a spell with this trait, you can't cast that spell with it again until you finish a long rest. This spell does not require a material component, and you can cast this spell using any spell slots you have of the appropriate level.",
    traittype: "spellgranted",
    options: {
      level: 1,
      school: ["divination","enchantment"]
    },
    cost: 3 },
  feystep: { 
    key: "feystep", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Fey Step", 
    description: "You can cast the misty step spell once using this trait. This trait can be used a number of times equal to your Proficiency Bonus per long rest.",
    cost: 6 },
  blessingoftheravenqueen: { 
    key: "blessingoftheravenqueen", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Blessing of the Raven Queen", 
    description: "Starting at 3rd level, you gain resistance to all damage when you teleport using the misty step spell. The resistance lasts until the start of your next turn. During that time, you appear ghostly and translucent.",
    enhances: "feystep",
    cost: 4 },
  feystepimprovement: { 
    key: "feystepimprovement", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Fey Step Improvement", 
    description: "Starting at 3rd level, the misty step spell gains one of the following traits, which can be changed after a long rest. The DC equals 8 + your Proficiency Bonus + your Spellcasting Ability modifier.",
    traittype: "choice",
    options: [
      {
        key: "autumn",
        title: "Autumn",
        description: "Immediately after you use misty step, up to two creatures of your choice that you can see within 10 feet of you must succeed on a Wisdom saving throw or be charmed by you for 1 minute, or until you or your companions deal any damage to the creatures."
      }, {
        key: "winter",
        title: "Winter",
        description: "When you use misty step, one creature of your choice that you can see within 5 feet of you before you teleport must succeed on a Wisdom saving throw or be frightened of you until the end of your next turn."
      }, {
      key: "spring",
      title: "Spring",
      description: "When you use misty step, you can touch one willing creature within 5 feet of you.That creature then teleports instead of you, appearing in an unoccupied space of your choice that you can see within 30 feet of you."
      }, {
        key: "summer",
        title: "Summer",
        description: "Immediately after you use misty step, each creature of your choice that you can see within 5 feet of you takes fire damage equal to your proficiency bonus."
    }],
    enhances: "feystep",
    cost: +2 },
  feycunning: { 
    key: "feycunning", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Fey Cunning", 
    description: "You have advantage on all Intelligence, Wisdom, and Charisma saving throws against magic.",
    cost: 7 },
  fairymagic: { 
    key: "fairymagic", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Fairy Magic", 
    description: "Starting at 3rd level, you can cast the faerie fire or enlarge/reduce spell (choose one) with this trait without a material component. Starting at 5th level, you can also cast the enlarge/reduce or invisibility spell (choose one) with this trait without a material component. Once you cast a spell with this trait, you can't cast that spell with it again until you finish a long rest. You can also cast either of those spells using any spell slots you have of the appropriate level.",
    traittype: "spellfromlist",
    options: [
      {
        level: 3,
        options: ["faeriefire", "enlargereduce"]
      }, {
        level: 5,
        options: ["enlargereduce", "invisibility"] 
      }
    ],
    cost: 8 },
  shapechanger: { 
    key: "shapechanger", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Shapechanger", 
    description: "As an action you can change your appearance and voice. You determine the specifics of the changes, including your hair length and sex. You also adjust your height and weight and can change your size between Medium and Small. You can make yourself appear as an individual of another race, and you must adopt a form that has the same basic arrangement of limbs that you have. Your clothing and equipment aren't changed by this trait. You stay into your new form until you use an action to revert to your true form or until you die.",
    cost: 8 },
  magicresistance: { 
    key: "magicresistance", 
    type: "bloodline", 
    subtype: "fey", 
    title: "Magic Resistance", 
    description: "You have advantage on saving throws against spells.",
    cost: 10 },
  fiendcantrip: { 
    key: "fiendcantrip", 
    type: "bloodline", 
    subtype: "fiend", 
    title: "Cantrip", 
    description: "You know one cantrip from the warlock spell list.",
    traittype: "spellgranted",
    options: {
      level: 0,
      classlist: "warlock"
    },
    duplicate: "cantrip",
    cost: 2 },
  fiendishresistance: { 
    key: "fiendishresistance", 
    type: "bloodline", 
    subtype: "fiend", 
    title: "Fiendish Resistance", 
    description: "You have resistance to one of the following damage types: cold, fire, or lightning.",
    traittype: "select",
    options: {
      type: "resistance",
      options: ["cold","fire","lightning"]
    },
    cost: 3 },
  fiendinnatemagic: { 
    key: "fiendinnatemagic", 
    type: "bloodline", 
    subtype: "fiend", 
    title: "Innate Magic", 
    description: "Choose one 1st-level spell from the warlock list. Once you cast a spell with this trait, you can't cast that spell with it again until you finish a long rest. This spell does not require a material component, and you can cast this spell using any spell slots you have of the appropriate level.",
    traittype: "spellgranted",
    options: {
      level: 1,
      classlist: "warlock"
    },
    cost: 3 },
  fearresistance: { 
    key: "fearresistance", 
    type: "bloodline", 
    subtype: "shadowborn", 
    title: "Fear Resistance", 
    description: "You have advantage on saving throws you make to avoid or end the frightened condition on yourself",
    cost: 2
  },
  deathlessnature: {
    key: "deathlessnature",
    type: "bloodline",
    subtype: "shadowborn",
    title: "Deathless Nature",
    description: "You don't need to breathe.",
    cost: 2
  },
  shadowborncantrip: { 
    key: "shadowborncantrip", 
    type: "bloodline", 
    subtype: "shadowborn", 
    title: "Cantrip", 
    description: "You know the chill touch, minor illusion, or primal savagery cantrip.",
    traittype: "spellfromlist",
    options: ["chilltouch","minorillusion","primalsavagery"],
    duplicate: "cantrip",
    cost: 2 },
  spiderclimb: {
    key: "spiderclimb",
    type: "bloodline",
    subtype: "shadowborn",
    title: "Spider Climb",
    description: "You have a climbing speed equal to your walking speed.",
    traittype: "property",
    options: {
      property: "speedclimbing",
      value: "Equal to walking"
    },
    cost: 2
  },
  necroticresistance: { 
    key: "necroticresistance", 
    type: "bloodline", 
    subtype: "shadowborn", 
    title: "Necrotic Resistance", 
    description: "You have resistance to necrotic damage.",
    cost: 3 },
  shadowborninnatemagic: { 
    key: "shadowborninnatemagic", 
    type: "bloodline", 
    subtype: "shadowborn", 
    title: "Innate Magic", 
    description: "Choose one 1st-level spell of your choice from the illusion or necromancy school of magic. You can cast the chosen spell once with this trait and regain the ability to do so when you finish a long rest. You can also cast this spell using any spell slots you have.",
    traittype: "spellfromlist",
    options: {
      level: 0,
      school: ["illusion", "necromancy"]
    },
    cost: 3 },
  closetodeath: { 
    key: "closetodeath", 
    type: "bloodline", 
    subtype: "shadowborn", 
    title: "Close to Death", 
    description: "You have advantage on death saving throws.",
    cost: 4 },
  camouflage: { 
    key: "camouflage", 
    type: "bloodline", 
    subtype: "shadowborn", 
    title: "Camouflage", 
    description: "When you make a Dexterity (Stealth) check, you make the check with advantage. You can use this trait a number of times equal to your Proficiency Bonus per long rest.",
    cost: 4 },
  shadowstep: { 
    key: "shadowstep", 
    type: "bloodline", 
    subtype: "shadowborn", 
    title: "Shadow Step", 
    description: "You can cast the misty step spell once using this trait. This trait can be used a number of times equal to your Proficiency Bonus per long rest.",
    cost: 6 },
  deepmagic: { 
    key: "deepmagic", 
    type: "bloodline", 
    subtype: "shadowborn", 
    title: "Deep Magic", 
    description: "Starting at 3rd level, you can cast the disguise self spell with this trait without a material component. Starting at 5th level, you can also cast the nondetection spell with this trait without a material component. Once you cast disguise self or nondetection with this trait, you can't cast that spell with it again until you finish a long rest. You can also cast either of those spells using any spell slots you have of the appropriate level.",
    traittype: "spellgranted",
    options: [
      {
        level: 3,
        options: ["disguiseself"]
      }, {
        level: 5,
        options: ["nondetection"]
      }
    ],
    cost: 4 },
  emissaryofthesea: { 
    key: "emissaryofthesea", 
    type: "bloodline", 
    subtype: "aquatic", 
    title: "Emissary of the Sea", 
    description: "You can communicate simple ideas to any Beast, Elemental, or Monstrosity that has a swimming speed. They can understand the meaning of your words, though you have no special ability to understand them in return.",
    cost: 1 },
  amphibious: { 
    key: "amphibious", 
    type: "bloodline", 
    subtype: "aquatic", 
    title: "Amphibious", 
    description: "You can breathe both air and water.",
    cost: 2 },
  aquaticcantrip: { 
    key: "aquaticcantrip", 
    type: "bloodline", 
    subtype: "aquatic", 
    title: "Cantrip", 
    description: "You know the shape water cantrip or the acid splash cantrip.",
    traittype: "spellfromlist",
    options: ["shapewater", "acidsplash"],
    duplicate: "cantrip",
    cost: 2 },
  swimspeed: { 
    key: "swimspeed", 
    type: "bloodline", 
    subtype: "aquatic", 
    title: "Swim Speed", 
    description: "You have a swim speed of 30 feet.",
    traittype: "property",
    options: {
      type: "swimspeed",
      value: "30 ft."
    },
    cost: 2 },
  aquaticresistance: { 
    key: "aquaticresistance", 
    type: "bloodline", 
    subtype: "aquatic", 
    title: "Aquatic Resistance", 
    description: "You have resistance to one of the following damage types: acid or cold.",
    traittype: "select",
    options: {
      type: "resistance",
      options: ["acid","cold"]
    },
    cost: 3 },
  shell: { 
    key: "shell", 
    type: "bloodline", 
    subtype: "aquatic", 
    title: "Shell", 
    description: "Due to your shell and the shape of your body, you are ill-suited to wearing armor. Your shell provides ample protection, however; it gives you a base AC of 17 (your Dexterity modifier doesn't affect this number). You gain no benefit from wearing armor, but if you are using a shield, you can apply the shield's bonus as normal.",
    duplicate: "naturalarmor",
    cost: 8 },
  claws: { 
    key: "claws", 
    type: "bloodline", 
    subtype: "feline", 
    title: "Claws", 
    description: "You can use your claws to make unarmed strikes. When you hit with them, the strike deals slashing damage equal to 1d6 + your Strength modifier, instead of the normal bludgeoning damage for an unarmed strike.",
    duplicate: "naturalweapons",
    cost: 1 },
  climbspeed: { 
    key: "climbspeed", 
    type: "bloodline", 
    subtype: "feline", 
    title: "Climb Speed", 
    description: "You have a climbing speed equal to your walking speed.",
    cost: 2 },
  felineleap: { 
    key: "felineleap", 
    type: "bloodline", 
    subtype: "feline", 
    title: "Feline Leap", 
    description: "Your long jump is 20 feet and your high jump is 10 feet, with or without a running start.",
    cost: 2 },
  catfall: { 
    key: "catfall", 
    type: "bloodline", 
    subtype: "feline", 
    title: "Catfall", 
    description: "When you fall and aren't incapacitated, you can make a DC 10 Dexterity (Acrobatics) check when you land. If you succeed, you take no falling damage and land on your feet.",
    cost: 3 },
  felineswiftness: { 
    key: "felineswiftness", 
    type: "bloodline", 
    subtype: "feline", 
    title: "Feline Swiftness", 
    description: "You can take the Dash action as a bonus action on each of your turns.",
    cost: 4 },
  roar: { 
    key: "roar", 
    type: "bloodline", 
    subtype: "feline", 
    title: "Roar", 
    description: "As a bonus action, you can let out an especially menacing roar. Creatures of your choice within 10 feet of you that can hear you must succeed on a Wisdom saving throw or become frightened of you until the end of your next turn. The DC of the save equals 8 + your Proficiency Bonus + your Constitution modifier. You can use this trait a number of times equal to your Proficiency Bonus, and you regain all expended uses when you finish a long rest.",
    cost: 6 },
  flyingnaturalweapons: { 
    key: "flyingnaturalweapons",
    type: "bloodline", 
    subtype: "flying", 
    title: "Natural Weapons", 
    description: "You have a feature that allows you to make damaging unarmed strikes. When you hit with it, the strike deals piercing damage equal to 1d6 + your Strength modifier, instead of the normal bludgeoning damage for an unarmed strike.",
    traittype: "choice",
    options: [{
      key: "fpo",
      title: "1",
      description: "FPO"
    }, {
      key: "fpo",
      title: "1",
      description: "FPO"
    }],
    duplicate: "naturalweapons", 
    cost: 1 },
  flyingcantrip: { 
    key: "flyingcantrip", 
    type: "bloodline", 
    subtype: "flying", 
    title: "Cantrip", 
    description: "You know the gust cantrip.",
    traittype: "spellgranted",
    options: ["gust"],
    duplicate: "cantrip", 
    cost: 2 },
  glide: { 
    key: "glide", 
    type: "bloodline", 
    subtype: "flying", 
    title: "Glide", 
    description: "While you aren't incapacitated, you fall at a rate of 60 feet per round and take no falling damage when you land.",
    cost: 3 },
  limitedflight: { 
    key: "limitedflight", 
    type: "bloodline", 
    subtype: "flying", 
    title: "Limited Flight", 
    description: "At level 1, you can use your bonus action to gain a flying speed equal to your walking speed for one turn, after which time you fall to the ground. At level 5, this ability increases to a flying speed of 60 feet for ten minutes. This ability is tiring, and can be used a number of times equal to your Proficiency Bonus per long rest. To use this ability, you can't be wearing medium or heavy armor.",
    cost: 5 },
  keensight: { 
    key: "keensight", 
    type: "bloodline", 
    subtype: "flying", 
    title: "Keen Sight", 
    description: "You have advantage on Wisdom (Perception) checks that rely on sight.",
    cost: 6 },
  wings: { 
    key: "wings", 
    type: "bloodline", 
    subtype: "flying", 
    title: "Wings", 
    description: "You have a flying speed equal to your walking speed. To use this speed, you can't be wearing medium or heavy armor.",
    traittype: "property",
    options: {
      type: "flyingspeed",
      value: "Walking speed."
    },
    cost: 12 },
  mammaliannaturalweapons: { 
    key: "mammaliannaturalweapons", 
    type: "bloodline", 
    subtype: "mammalian", 
    title: "Natural Weapons", 
    description: "You have a feature that allows you to make damaging unarmed strikes. When you hit with it, the strike deals 1d6 damage of the type indicated + the modifier indicated instead of the normal bludgeoning damage + Strength for an unarmed strike.",
    traittype: "choice",
    options: [{
      key: "fpo",
      title: "1",
      description: "FPO"
    }, {
      key: "fpo",
      title: "1",
      description: "FPO"
    }],
    duplicate: "naturalweapons", 
    cost: 1 },
  leap: { 
    key: "leap", 
    type: "bloodline", 
    subtype: "mammalian", 
    title: "Leap", 
    description: "Your long jump is 20 feet and your high jump is 10 feet, with or without a running start.",
    cost: 2 },
  charge: { 
    key: "charge", 
    type: "bloodline", 
    subtype: "mammalian", 
    title: "Charge", 
    description: "Immediately after you use the Dash action on your turn and move at least 20 feet, you can make one unarmed strike melee attack as a bonus action.",
    cost: 3 },
  dextrous: { 
    key: "dextrous", 
    type: "bloodline", 
    subtype: "mammalian", 
    title: "Dextrous", 
    description: "Due to your prehensile tail or feet with opposable thumbs you can use an object as a bonus action, or hold an extra weapon with the light property.",
    cost: 3 },
  trunk: { 
    key: "trunk", 
    type: "bloodline", 
    subtype: "mammalian", 
    title: "Trunk", 
    description: "You can grasp things with your trunk, and you can use it as a snorkel. It has a reach of 5 feet, and it can lift a number of pounds equal to five times your Strength score. You can use it to do the following simple tasks: lift, drop, hold, push, or pull an object or a creature; open or close a door or a container; grapple someone; or make an unarmed strike.<br/><br/>Your trunk can't wield weapons or shields or do anything that requires manual precision, such as using tools or magic items or performing the somatic components of a spell.",
    cost: 3 },
  keensmell: { 
    key: "keensmell", 
    type: "bloodline", 
    subtype: "mammalian", 
    title: "Keen Smell", 
    description: "Thanks to your keen sense of smell, you have advantage on Wisdom (Perception), Wisdom (Survival), and Intelligence (Investigation) checks that involve smell.",
    cost: 3 },
  packtactics: { 
    key: "packtactics", 
    type: "bloodline", 
    subtype: "mammalian", 
    title: "Pack Tactics", 
    description: "You have advantage on an attack roll against a creature if at least one of your allies is within 5 feet of the creature and the ally isn't incapacitated.",
    cost: 8 },
  holdbreath: { 
    key: "holdbreath", 
    type: "bloodline", 
    subtype: "reptilian", 
    title: "Hold Breath", 
    description: "You can hold your breath for up to 1 hour at a time.",
    cost: 1 },
  reptiliannaturalweapons: { 
    key: "reptiliannaturalweapons", 
    type: "bloodline", 
    subtype: "reptilian", 
    title: "Natural Weapons", 
    description: "You can use your toothy maw, fangs, or claws to make unarmed strikes. When you hit with them, the strike deals 1d6 damage of the type indicated + the modifier indicated instead of the bludgeoning damage done by normal unarmed strikes.",
    traittype: "choice",
    options: [{
      key: "fpo",
      title: "1",
      description: "FPO"
    }, {
      key: "fpo",
      title: "1",
      description: "FPO"
    }],
    duplicate: "naturalweapons", 
    cost: 1 },
  hungryjaws: { 
    key: "hungryjaws", 
    type: "bloodline", 
    subtype: "reptilian", 
    title: "Hungry Jaws", 
    description: "As a bonus action, you can make a special attack with your bite. If the attack hits, it deals normal damage, and you gain temporary hit points (minimum of 1) equal to your Proficiency Bonus. This trait can be used a number of times equal to your Proficiency Bonus per long rest.",
    cost: 3 },
  reptiliannaturalarmor: { 
    key: "reptiliannaturalarmor", 
    type: "bloodline", 
    subtype: "reptilian", 
    title: "Natural Armor", 
    description: "You can calculate your AC as 13 + your Dexterity modifier. A shield's benefits apply as normal while you use your natural armor.",
    duplicate: "naturalarmor", 
    cost: 3 },
  camouflage: { 
    key: "camouflage", 
    type: "bloodline", 
    subtype: "reptilian", 
    title: "Camouflage", 
    description: "As long as you don't move, you have advantage on Dexterity (Stealth) checks and can attempt to hide even when you are only lightly obscured.",
    cost: 4 },
  shell: { 
    key: "shell", 
    type: "bloodline", 
    subtype: "reptilian", 
    title: "Shell", 
    description: "Due to your shell and the shape of your body, you are ill-suited to wearing armor. Your shell provides ample protection, however; it gives you a base AC of 17 (your Dexterity modifier doesn't affect this number). You gain no benefit from wearing armor, but if you are using a shield, you can apply the shield's bonus as normal.",
    duplicate: "naturalarmor",
    cost: 8 },
  toxinresilience: { 
    key: "toxinresilience", 
    type: "bloodline", 
    subtype: "construct", 
    title: "Toxin Resilience", 
    description: "You have advantage on saving throws you make to avoid or end the poisoned or diseased conditions on yourself.",
    cost: 2 },
  vigilantrest: { 
    key: "vigilantrest", 
    type: "bloodline", 
    subtype: "construct", 
    title: "Vigilant Rest", 
    description: "When you take a long rest, you can spend at least six hours in an inactive, motionless state, rather than sleeping. In this state, you appear inert, but it doesn't render you unconscious, and you can see and hear as normal.",
    cost: 2 },
  constructpoisonresistance: { 
    key: "constructpoisonresistance", 
    type: "bloodline", 
    subtype: "construct", 
    title: "Poison Resistance", 
    description: "You are resistant to poison damage.",
    cost: 3 },
  constructednature: { 
    key: "constructednature", 
    type: "bloodline", 
    subtype: "construct", 
    title: "Constructed Nature", 
    description: "You don't need to eat, drink, breathe, and magic can't put you to sleep. Additionally, you are immune to disease.",
    cost: 3 },
  integratedprotection: { 
    key: "integratedprotection", 
    type: "bloodline", 
    subtype: "construct", 
    title: "Integrated Protection", 
    description: "You gain a +1 bonus to Armor Class.",
    duplicate: "naturalarmor",
    cost: 7 },
  draconicancestry: {
    key: "draconicancestry",
    type: "bloodline",
    subtype: "draconic",
    title: "Draconic Ancestry",
    description: "If you have draconic ancestry, you have a special magical affinity and must take this trait. Choose one of the following damage types: acid, cold, fire, force, lightning, necrotic, poison, psychic, radiant, or thunder",
    traittype: "select",
    options: ["acid", "cold", "fire", "force", "lightning", "necrotic", "poison", "psychic", "radiant", "thunder"],
    cost: 0 },
  draconiccantrip: { 
    key: "draconiccantrip", 
    type: "bloodline", 
    subtype: "draconic", 
    title: "Cantrip", 
    description: "You know one cantrip of your choice from the sorcerer spell list.",
    traittype: "spellgranted",
    options: {
      level: 0,
      classlist: "sorcerer"
    },
    duplicate: "cantrip",
    cost: 2 },
  draconicresistance: { 
    key: "draconicresistance", 
    type: "bloodline", 
    subtype: "draconic", 
    title: "Draconic Resistance", 
    description: "You have resistance to the damage type associated with your draconic ancestry.",
    cost: 3 },
  draconicpresence: { 
    key: "draconicpresence", 
    type: "bloodline", 
    subtype: "draconic", 
    title: "Draconic Presence", 
    description: "You have advantage on Charisma (Intimidation) checks.",
    cost: 4 },
  draconicwarding: { 
    key: "draconicwarding", 
    type: "bloodline", 
    subtype: "draconic", 
    title: "Draconic Warding", 
    description: "Starting at 5th level, as an action, you can channel your draconic energy to protect yourself. For 1 minute, you become immune to the damage type associated with your draconic ancestry. You can't use this feature again until you finish a long rest.",
    cost: 4 },
  draconiccry: { 
    key: "draconiccry", 
    type: "bloodline", 
    subtype: "draconic", 
    title: "Draconic Cry", 
    description: "As a bonus action, you let out a cry at your enemies within 10 feet of you. Until the start of your next turn, you and your allies have advantage on attack rolls against any of those creatures who could hear you. You can use this trait a number of times equal to your Proficiency Bonus per long rest.",
    cost: 5 },
  breathweapon: { 
    key: "breathweapon", 
    type: "bloodline", 
    subtype: "draconic", 
    title: "Breath Weapon", 
    description: "When you take the Attack action, you can replace one of your attacks with an exhalation of a magical energy in a 15-foot cone. Each creature in the area must make a Dexterity saving throw against a DC equal to 8 + your Constitution modifier + your Proficiency Bonus.<br/><br/>A creature takes 1d10 damage of the type associated with your Draconic Ancestry on a failed save, and half as much damage on a successful one. The damage increases to 2d10 at 5th level, 3d10 at 11th level, and 4d10 at 17th level. You can use this trait a number of times equal to your Proficiency Bonus, and you regain all expended uses when you finish a long rest.",
    cost: 6 },
  enhancedbreathweapon: { 
    key: "enhancedbreathweapon", 
    type: "bloodline", 
    subtype: "draconic", 
    title: "Enhanced Breath Weapon", 
    description: "At 5th level, you gain a breath weapon. When you take the Attack action on your turn you can replace one of your attacks with an exhalation of magical energy in a 15-foot cone. The save DC is 8 + the skill modifier + your Proficiency bonus. Whenever you use it, choose one:",
    options: { },
    cost: 6 },
  psioniccantrip: { 
    key: "psioniccantrip", 
    type: "bloodline", 
    subtype: "psionic", 
    title: "Cantrip", 
    description: "You know the mage hand cantrip. The hand is invisible and doesn't require components when you cast it with this trait.",
    traittype: "spellgranted",
    options: ["magehand"],
    duplicate: "cantrip",
    cost: 2 },
  psionicresistance: { 
    key: "psionicresistance", 
    type: "bloodline", 
    subtype: "psionic", 
    title: "Psionic Resistance", 
    description: "You have resistance to one of the following damage types: force or psychic.",
    cost: 3 },
  psionicinnatemagic: { 
    key: "psionicinnatemagic", 
    type: "bloodline", 
    subtype: "psionic", 
    title: "Innate Magic", 
    description: "Choose one 1st-level spell on the Sorcerer spell list from the abjuration or transmutation school of magic. You can cast the chosen spell once with this trait and regain the ability to do so when you finish a long rest. The spell doesn't require components when you cast it with this trait. You can also cast this spell using any appropriate spell slots you have.",
    traittype: "spellgranted",
    options: {
      level: 1,
      classlist: "sorcerer",
      school: ["abjuration","transmutation"]
    },
    cost: 3 },
  psychicresistance: { 
    key: "psychicresistance", 
    type: "bloodline", 
    subtype: "psionic", 
    title: "Psychic Resistance", 
    description: "You have advantage on saving throws you make to avoid or end the charmed or frightened conditions on yourself.",
    cost: 4 },
  telepathy: { 
    key: "telepathy", 
    type: "bloodline", 
    subtype: "psionic", 
    title: "Telepathy", 
    description: "You can speak telepathically to any creature within 30 feet of you. The creature understands you only if the two of you share a language. You can speak telepathically in this way to one creature at a time.",
    cost: 5 },
  psionicmagic: { 
    key: "psionicmagic", 
    type: "bloodline", 
    subtype: "psionic", 
    title: "Psionic Magic", 
    description: "Once you cast a spell with this trait, you can't cast that spell with it again until you finish a long rest. You can also cast either of those spells using any spell slots you have of the appropriate level. Pick one of the two combinations of spells:",
    traittype: "selectspellset",
    options: {},
    cost: 8 },
  toxinresilience: { 
    key: "toxinresilience", 
    type: "bloodline", 
    subtype: "stout", 
    title: "Toxin Resilience", 
    description: "You have advantage on saving throws you make to avoid or end the poisoned or diseased conditions on yourself.",
    cost: 2 },
  stoutpoisonresistance: { 
    key: "stoutpoisonresistance", 
    type: "bloodline", 
    subtype: "stout", 
    title: "Poison Resistance", 
    description: "You are resistant to poison damage.",
    cost: 3 },
  stoutnaturalarmor: { 
    key: "stoutnaturalarmor", 
    type: "bloodline", 
    subtype: "stout", 
    title: "Natural Armor", 
    description: "You have thick skin. You can calculate your AC as 12 + your Constitution modifier. A shield's benefits apply as normal while you use your natural armor.",
    duplicate: "naturalarmor",
    cost: 3 },
  relentless: { 
    key: "relentless", 
    type: "bloodline", 
    subtype: "stout", 
    title: "Relentless", 
    description: "When you are reduced to 0 hit points but not killed outright, you can drop to 1 hit point instead. You can't use this feature again until you finish a long rest.",
    cost: 4 },
  toughness: { 
    key: "toughness", 
    type: "bloodline", 
    subtype: "stout", 
    title: "Toughness", 
    description: "Your hit point maximum increases by 1, and it increases by 1 every time you gain a level.",
    cost: 5 },
  durable: { 
    key: "durable", 
    type: "bloodline", 
    subtype: "stout", 
    title: "Durable", 
    description: "When you take damage, you can use your reaction to roll a d12. Add your Constitution modifier to the number rolled and reduce the damage by that total. This trait can be used a number of times equal to your Proficiency Bonus per long rest.",
    cost: 7 },
  toolproficiency: { 
    key: "toolproficiency", 
    type: "culture", 
    subtype: "artisan", 
    title: "Tool Proficiency", 
    description: "You gain proficiency with the artisan's tools of your choice.",
    cost: 1 },
  artisancantrip: { 
    key: "artisancantrip", 
    type: "culture", 
    subtype: "artisan", 
    title: "Cantrip", 
    description: "You know the mending or guidance cantrip.",
    traittype: "spellfromlist",
    options: ["mending", "guidance"],
    duplicate: "cantrip", 
    cost: 2 },
  giftedartisan: { 
    key: "giftedartisan", 
    type: "culture", 
    subtype: "artisan", 
    title: "Gifted Artisan", 
    description: "When you make an ability check using an artisan's tool with which you are proficient, you can roll one a d4 and add the number rolled to the ability check.",
    cost: 2 },
  artisanslore:{key:"artisanslore",type:"culture",subtype:"artisan",title:"Artisan's Lore",description:"Whenever you make an Intelligence (History) check related to the origin of an item related to an artisan tool with which you are proficient, you are considered proficient in the History skill and add double your Proficiency Bonus to the check, instead of your normal Proficiency Bonus.",cost: 3},
artisanskillproficiency:{ 
  key:"artisanskillproficiency", 
  type:"culture", 
  subtype:"artisan", 
  title:"Skill Proficiency", description:"You gain proficiency with one of the following skills of your choice: Athletics, Arcana, History, Insight, Persuasion, Sleight of Hand.",
  cost: 3},
  toolproficiency: { 
    key: "toolproficiency", 
    type: "culture", 
    subtype: "criminal", 
    title: "Tool Proficiency", 
    description: "You gain proficiency with a gaming set or one set of tools of your choice: thieves' tools, disguise kit, forgery kit, poisoner's kit.",
    cost: 1 },
  criminalcantrip: { 
    key: "criminalcantrip", 
    type: "culture", 
    subtype: "criminal", 
    title: "Cantrip", 
    description: "You know one cantrip from the bard spell list.",
    traittype: "spellgranted",
    options: {
      level: 0,
      classlist: "bard"
    },
    duplicate: "cantrip", 
    cost: 2 },
  expertforgery: { 
    key: "expertforgery", 
    type: "culture", 
    subtype: "criminal", 
    title: "Expert Forgery", 
    description: "You can duplicate other creatures' handwriting and craftwork. You have advantage on all checks made to produce forgeries or duplicates of existing objects.",
    cost: 2 },
  sneaky: {
    key: "sneaky",
    type: "culture",
    subtype: "criminal",
    title: "Sneaky",
    description: "You are proficient in the Stealth skill. In addition, without squeezing, you can move through and stop in a space large enough for a Small creature.",
    cost: 2,
  },
  criminalcamoflage: {
    key: "criminalcamoflage",
    type: "culture",
    subtype: "criminal",
    title: "Camoflage",
    description: "When you make a Dexterity (Stealth) check, you can make the check with advantage. You can use this trait a number of times equal to your proficiency bonus, and you regain all expended uses when you finish a long rest.",
    cost: 2
  },
  criminalskillproficiency: { 
    key: "criminalskillproficiency", 
    type: "culture", 
    subtype: "criminal", 
    title: "Skill Proficiency", 
    description: "You have proficiency in one of the following skills of your choice: Deception, Insight, Investigation, Performance, Sleight of Hand, Stealth, Intimidation, or Persuasion.",
    cost: 3 },
  mergewithshadows: { 
    key: "mergewithshadows", 
    type: "culture", 
    subtype: "criminal", 
    title: "Merge with Shadows", 
    description: "You can cast the pass without trace spell once with this trait and you regain the ability to do so when you finish a long rest. You can also cast this spell using any spell slots you have.",
    cost: 4 },
  thiefsintuition:{key:"thiefsintuition",type:"culture",subtype:"criminal",title:"Thief's Intuition",description:"When you make an ability check using thieves' tools, you can roll a d4 and add the number rolled to the ability check.",cost: 4},
skilled: { 
  key: "skilled", 
  type: "culture", 
  subtype: "criminal", 
  title: "Skilled", 
  description: "When you make an ability check using a skill in which you have proficiency, you can give yourself advantage on the check before rolling a d20. You can give yourself advantage in this way a number of times equal to your Proficiency Bonus per long rest.",
  cost: 6 },
toolproficiency: { 
  key: "toolproficiency", 
  type: "culture", 
  subtype: "friendly", 
  title: "Tool Proficiency", 
  description: "You gain proficiency with one type of gaming set, musical instrument of your choice, a Cook's Utensils, or Herbalism Kit.",
  cost: 1 },
giftedentertainer: { 
  key: "giftedentertainer", 
  type: "culture", 
  subtype: "friendly", 
  title: "Gifted Entertainer", 
  description: "When you make an ability check using a gaming set or musical instrument with which you are proficient, you can roll one a d4 and add the number rolled to the ability check.",
  cost: 2 },
entertainerslore:{
  key:"entertainerslore",
  type:"culture",
  subtype:"friendly",
  title:"Entertainer's Lore",
  description:"Whenever you make an Intelligence (History) check related to the origin of a tale related to a gaming set or musical instrument with which you are proficient, you are considered proficient in the History skill and add double your Proficiency Bonus to the check, instead of your normal Proficiency Bonus.",
  cost: 3},
friendlyskillproficiency: { 
  key: "friendlyskillproficiency", 
  type: "culture", 
  subtype: "friendly", 
  title: "Skill Proficiency", 
  description: "You gain proficiency with one of the following skills of your choice: Acrobatics, Deception, Insight, Medicine, Performance, Persuasion.",
  cost: 3 },
healersintuition:{
  key:"healersintuition",
  type:"culture",
  subtype:"friendly",
  title:"Healer's Intuition",
  description:"When you make a Wisdom (Medicine) check or an ability check using an herbalism kit, you can roll with advantage.",
  cost: 4},
magecantrip: { 
  key: "magecantrip", 
  type: "culture", 
  subtype: "mage", 
  title: "Cantrip", 
  description: "You learn one cantrip of your choice from the wizard spell list.",
  traittype: "spellgranted",
  options: {
    level: 0,
    classlist: "wizard"
  },
  duplicate: "cantrip", 
  cost: 2 },
learnedmagic: { 
  key: "learnedmagic", 
  type: "culture", 
  subtype: "mage", 
  title: "Learned Magic", 
  description: "Choose one 1st-level spell from the wizard spell list. You can cast the chosen spell once with this trait and regain the ability to do so when you finish a long rest. You can also cast this spell using any spell slots you have.",
  traittype: "spellgranted",
  options: {
    level: 1,
    classlist: "wizard"
  },
  cost: 3 },
destructivespell: { 
  key: "destructivespell", 
  type: "culture", 
  subtype: "mage", 
  title: "Destructive Spell", 
  description: "When you damage a creature with a spell, you can cause the spell to deal extra damage equal to 1d4 per point of your Proficiency Bonus to a single target of the spell. This trait can be used a number of times equal to your Proficiency Bonus per long rest.",
  cost: 3 },
cultureskillproficiency: { 
  key: "cultureskillproficiency", 
  type: "culture", 
  subtype: "mage", 
  title: "Skill Proficiency", 
  description: "You have proficiency in one of the following skills of your choice: Arcana, History, Investigation, Nature, Religion",
  cost: 3 },
skirmishersspeed:{key:"skirmishersspeed",type:"culture",subtype:"skirmisher",title:"Skirmisher's Speed",description:"Your base walking speed increases by 5 feet.",cost: 2},
adrenalinerush: { 
  key: "adrenalinerush", 
  type: "culture", 
  subtype: "skirmisher", 
  title: "Adrenaline Rush", 
  description: "You can take the Dash action as a bonus action. You can use this trait a number of times equal to your Proficiency bonus per long rest. Whenever you use this trait, gain a number of temporary hit points equal to your proficiency bonus.",
  cost: 3 },
lethalstrike: { 
  key: "lethalstrike", 
  type: "culture", 
  subtype: "skirmisher", 
  title: "Lethal Strike", 
  description: "When you damage a creature with a weapon attack, you can cause the attack to deal extra damage equal to 1d4 per point of your Proficiency Bonus. This trait can be used a number of times equal to your Proficiency Bonus per long rest.",
  cost: 3 },
skirmisherskillproficiency: { 
  key: "skirmisherskillproficiency", 
  type: "culture", 
  subtype: "skirmisher", 
  title: "Skill Proficiency", 
  description: "You have proficiency in one of the following skills of your choice: Athletics, Insight, Nature, Perception, Stealth, or Survival.",
  traittype: "selectproficiency",
  options: ["athletics","insight","nature","perception","stealth","survival"],
  cost: 3 },
surpriseattack: { 
  key: "surpriseattack", 
  type: "culture", 
  subtype: "skirmisher", 
  title: "Surprise Attack", 
  description: "If you hit a creature with an attack roll, the creature takes an extra 2d6 damage if it hasn't taken a turn yet in the current combat.",
  cost: 5 },
nimbleescape: { 
  key: "nimbleescape", 
  type: "culture", 
  subtype: "skirmisher", 
  title: "Nimble Escape", 
  description: "You can take the Disengage or Hide action as a bonus action on each of your turns.",
  cost: 7 },
speechofbeastandleaf: { 
  key: "speechofbeastandleaf", 
  type: "culture", 
  subtype: "survivalist", 
  title: "Speech of Beast and Leaf", 
  description: "You have the ability to communicate in a limited manner with Beasts, Plants, and vegetation. They can understand the meaning of your words, though you have no special ability to understand them in return. You have advantage on all Charisma checks you make to influence them.",
  cost: 2 },
survivalistcantrip: { 
  key: "survivalistcantrip", 
  type: "culture", 
  subtype: "survivalist", 
  title: "Cantrip", 
  description: "You know one cantrip from the druid spell list.",
  traittype: "spellgranted",
  options: {
    level: 0,
    classlist: "druid"
  },
  duplicate: "cantrip", 
  cost: 2 },
naturalmagic: { 
  key: "naturalmagic", 
  type: "culture", 
  subtype: "survivalist", 
  title: "Natural Magic", 
  description: "Choose one 1st-level spell from the druid spell list. You can cast the chosen spell once with this trait and regain the ability to do so when you finish a long rest. You can also cast this spell using any spell slots you have.",
  traittype: "spellgranted",
  options: {
    level: 1,
    classlist: "druid"
  },
  cost: 3 },
beasttracker: { 
  key: "beasttracker", 
  type: "culture", 
  subtype: "survivalist", 
  title: "Beast Tracker", 
  description: "Whenever you make a Wisdom (Survival) check to track beasts, you are considered proficient in the Survival skill and add double your Proficiency Bonus to the check, instead of your normal Proficiency Bonus.",
  cost: 3 },
survivalistskillproficiency: { 
  key: "survivalistskillproficiency", 
  type: "culture", 
  subtype: "survivalist", 
  title: "Skill Proficiency", 
  description: "You have proficiency in one of the following skills of your choice: Animal Handling, Medicine, Nature, Perception, Stealth, or Survival.",
  cost: 3 },
keensenses: { 
  key: "keensenses", 
  type: "culture", 
  subtype: "survivalist", 
  title: "Keen Senses", 
  description: "You have advantage on Wisdom (Perception) checks that rely on hearing or sight.",
  cost: 6 },
brave: { 
  key: "brave", 
  type: "culture", 
  subtype: "warrior", 
  title: "Brave", 
  description: "You have advantage on saving throws to avoid or end the frightened condition on yourself.",
  cost: 2 },
aggressive: { 
  key: "aggressive", 
  type: "culture", 
  subtype: "warrior", 
  title: "Aggressive", 
  description: "As a bonus action, you can move up to your speed toward an enemy of your choice that you can see or hear. You must end this move closer to the enemy than you started.",
  cost: 3 },
savageattacks: { 
  key: "savageattacks", 
  type: "culture", 
  subtype: "warrior", 
  title: "Savage Attacks", 
  description: "When you score a critical hit with a melee weapon attack, you can roll one of the weapon's damage dice one additional time and add it to the extra damage of the critical hit.",
  cost: 3 },
combattraining: { 
  key: "combattraining", 
  type: "culture", 
  subtype: "warrior", 
  title: "Combat Training", 
  description: "You gain proficiency in 2 simple weapons of your choice.",
  cost: 2 },
martialtraining: { 
  key: "martialtraining", 
  type: "culture", 
  subtype: "warrior", 
  title: "Martial Training", 
  description: "You gain proficiency in 2 martial weapons of your choice.",
  cost: 3 },
lightarmorproficiency: { 
  key: "lightarmorproficiency", 
  type: "culture", 
  subtype: "warrior", 
  title: "Light Armor Proficiency", 
  description: "You have proficiency with light armor.",
  cost: 1 },
mediumarmorproficiency: { 
  key: "mediumarmorproficiency", 
  type: "culture", 
  subtype: "warrior", 
  title: "Medium Armor Proficiency", 
  description: "You have proficiency with light and medium armor.",
  cost: 4 },
heavyarmortraining: { 
  key: "heavyarmortraining", 
  type: "culture", 
  subtype: "warrior", 
  title: "Heavy Armor Training", 
  description: "Your speed is not reduced by wearing heavy armor.",
  cost: 2 },
toolproficiency: { 
  key: "toolproficiency", 
  type: "culture", 
  subtype: "waterborne", 
  title: "Tool Proficiency", 
  description: "You gain proficiency with one tool of your choice: carpenter's tools, navigator's tools, or vehicles (water).",
  cost: 1 },
weatherworn: { 
  key: "weatherworn", 
  type: "culture", 
  subtype: "waterborne", 
  title: "Weather Worn", 
  description: "You do not suffer disadvantage on perception checks due to heavy precipitation, as described in chapter 5 of the Dungeon Master's Guide.",
  cost: 1 },
waterbornecantrip: { 
  key: "waterbornecantrip", 
  type: "culture", 
  subtype: "waterborne", 
  title: "Cantrip", 
  description: "You know the gust or mending cantrip.",
  traittype: "spellfromlist",
  options: ["gust", "mending"],
  duplicate: "cantrip",
  cost: 2 },
swimspeed: { 
  key: "swimspeed", 
  type: "culture", 
  subtype: "waterborne", 
  title: "Swim Speed", 
  description: "You have a swim speed of 30 feet.",
  cost: 2 },
waterborneskillproficiency: { 
  key: "waterborneskillproficiency", 
  type: "culture", 
  subtype: "waterborne", 
  title: "Skill Proficiency", 
  description: "You have proficiency in one of the following skills of your choice: Acrobatics, Athletics, Perception, Nature, Sleight of Hand, Survival.",
  cost: 3 },
marinerslore:{key:"marinerslore",type:"culture",subtype:"waterborne",title:"Mariner's Lore",description:"Whenever you make an Intelligence (History) or Intelligence (Religion) check related to the sea or water vehicles, you are considered proficient in the History or Religion skill and add double your Proficiency Bonus to the check, instead of your normal Proficiency Bonus.",cost: 4},
sealegs: { 
  key: "sealegs", 
  type: "culture", 
  subtype: "waterborne", 
  title: "Sea Legs", 
  description: "You have advantage on Dexterity (Acrobatics) checks.",
  cost: 6 },
serenity: { 
  key: "serenity", 
  type: "culture", 
  subtype: "theocratic", 
  title: "Serenity", 
  description: "You have advantage on saving throws to avoid or end the charmed or frightened conditions on yourself, and to resist the effects of madness.",
  cost: 4 },
religiousintuition: { 
  key: "religiousintuition", 
  type: "culture", 
  subtype: "theocratic", 
  title: "Religious Intuition", 
  description: "You have advantage on Intelligence (Religion) checks.",
  cost: 4 },
theocraticcantrip: { 
  key: "theocraticcantrip", 
  type: "culture", 
  subtype: "theocratic", 
  title: "Cantrip", 
  description: "You know one cantrip from the cleric spell list.",
  traittype: "spellgranted",
  options: {
    level: 0,
    classlist: "cleric"
  },
  duplicate: "cantrip", 
  cost: 2 },
devoutmagic: { 
  key: "devoutmagic", 
  type: "culture", 
  subtype: "theocratic", 
  title: "Devout Magic", 
  description: "Choose one 1st-level spell from the cleric spell list. You can cast the chosen spell once with this trait and regain the ability to do so when you finish a long rest. You can also cast this spell using any spell slots you have.",
  traittype: "spellgranted",
  options: {
    level: 1,
    classlist: "warlock"
  },
  cost: 3 },
theocraticskillproficiency: { 
  key: "theocraticskillproficiency", 
  type: "culture", 
  subtype: "theocratic", 
  title: "Skill Proficiency", 
  description: "You have proficiency in one of the following skills of your choice: Religion, History, Insight, Persuasion, Deception, Medicine",
  cost: 3 },
}